GET https://backend-server-shx1.onrender.com/add_trasaction?category=Electricity

###
DELETE https://backend-server-shx1.onrender.com/add_trasaction/4

###

POST https://backend-server-shx1.onrender.com/add_trasaction
Content-Type: application/json;

{
    "id":1,
    "amount":10000,
    "date":"2023-05-13",
    "time":"16:25",
    "comment": "",
    "withdraw_from":"Credit",
    "category": "Grocery"
}