GET https://backend-server-shx1.onrender.com/add_account-1

###
DELETE https://backend-server-shx1.onrender.com/add_account/1

###

https://backend-server-shx1.onrender.com/add_trasaction/1
Content-Type: application/json;

{
    "id":1,
    "amount":10000,
    "date":"2023-05-13",
    "time":"16:25",
    "comment": "",
    "withdraw_from":"Credit",
    "category": "Grocery"
}

###
POST https://backend-server-shx1.onrender.com/add_account
Content-Type: application/json

{
      "id":1,
      "accountname": "",
      "amount": 0,
      "group": "",
      "iconcolor": "",
      "iconclass": ""
}